### ISSUE TITLE
Potential Circular Import

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [karim88/PlankSetting#7]
After installing this on Linux Mint 20, with all dependencies installed, I am getting this error when I run planksetting:
```
Traceback (most recent call last):
  File "/usr/share/planksetting/planksetting.py", line 3, in <module>
    from planksetting import Gtk
  File "/usr/share/planksetting/planksetting.py", line 3, in <module>
    from planksetting import Gtk
ImportError: cannot import name 'Gtk' from partially initialized module 'planksetting' (most likely due to a circular import) (/usr/share/planksetting/planksetting.py)
```

Seems there is a circular import, likely (but not definitely) related to the program "planksetting" importing a module called "planksetting". That's my best guess, but I don't know for certain.

**Comment by ouladck** [comment]
Hi @HeyITGuyFixIt, Thanks for reporting this issue, can you please give me what command did you run to get this error?
so I can reproduce the same error.

**Comment by HeyITGuyFixIt** [comment]
I installed it per README.md, and then ran `planksetting14` on its own and got that error.
